import { Geist, Geist_Mono, Ubuntu } from "next/font/google";
import "@ant-design/v5-patch-for-react-19";
import { Metadata } from "next";
import "../globals.css";
import Navigation from "../../components/landing/Navigation";
import { headers } from "next/headers";
import Footer from "../../components/landing/Footer";
import { GlobalStateProvider } from "../../contexts/GlobalStateContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = await headers();
  const studentId = header.get("x-student-id");

  return (
    <html lang="en">
      <body
        style={{
          background:
            "radial-gradient(ellipse at 50% 10%, #06142E 0%, #123AA9 57%, #182F56 100%)",
        }}
        className={`min-h-screen w-full ${geistSans.variable} ${geistMono.variable} ${ubuntu.variable} antialiased`}
      >
        <GlobalStateProvider initialNim={studentId || undefined}>
          <Navigation studentId={studentId} />
          {children}
          <Footer />
        </GlobalStateProvider>
      </body>
    </html>
  );
}
